services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - statcraft

  backend:
    build:
      context: ./backend
    command: gunicorn statCraft.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - statcraft

  frontend:
    build:
      context: ./frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./.env
    networks:
      - statcraft
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/prod.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - statcraft

networks:
  statcraft:

volumes:
  db-data:
